### ISSUE TITLE
"Malformed .pgen file" when exporting from bgen

### ISSUE THREAD

**Issue by azenin** [chrchang/plink-ng#55] opened 2017-11-10 16:06 UTC
Hi,

I am trying to export a portion of bgen+sample to transposed .traw format:
`plink2 --bgen inputfile.bgen --sample inputfile.sample --keep input.sample --maf 0.001 --export A-transpose --out test`
it successfully exported bgen+sample to temporary psam+pgen+pvar but failed on calculating frequencies stage with error and exits:
```
Calculating allele frequencies... 0%
Error: Malformed .pgen file.
```

I got `PLINK v2.00aLM 64-bit Intel (4 Nov 2017)` and Ubuntu 16.04 LTS, previous `PLINK v2.00aLM 64-bit Intel (16 Oct 2017)` version works fine.

**Comment by chrchang** [comment] 2017-11-10 18:12
Okay, can you send me a test dataset to replicate this bug with?

**Comment by chrchang** [comment] 2017-11-13 20:45
Failing that, can you at least give me the full .log file output?  I was unable to reproduce the error with my test .bgen files (both v1.1 and v1.2), so it would be very helpful to at least see e.g. the dimensions of your files, the number of samples remaining after --keep, etc.  Otherwise, I have no choice but to wait until someone else runs into the same problem.

**Comment by azenin** [comment] 2017-11-14 10:51
I can't provide you data, but here is log file
```
PLINK v2.00aLM 64-bit Intel (4 Nov 2017)
Options in effect:
  --bgen chr05_052912257-109517751.bgen
  --export A-transpose
  --keep clean.sample
  --maf 0.001
  --out test
  --sample chr05_052912257-109517751.sample

Hostname: master
Working directory: /mnt/tmp
Start time: Mon Nov 13 23:56:40 2017

Random number seed: 1510606600
122877 MB RAM detected; reserving 61438 MB for main workspace.
Using up to 16 threads (change this with --threads).
--bgen: 1800000 variants detected, format v1.1.
32062 samples imported from .sample file to test-temporary.psam .
--bgen: test-temporary.pgen + test-temporary.pvar written.
32062 samples (0 females, 0 males, 32062 ambiguous; 32062 founders) loaded from
test-temporary.psam.
1800000 variants loaded from test-temporary.pvar.
Note: No phenotype data present.
--keep: 18320 samples remaining.
18320 samples (0 females, 0 males, 18320 ambiguous; 18320 founders) remaining
after main filters.
Calculating allele frequencies...
Error: Malformed .pgen file.

End time: Mon Nov 13 23:59:11 2017
```

**Comment by azenin** [comment] 2017-11-14 10:55
`clean.sample` is 18383 lines long and some samples can't be found in input bgen, maybe this can be the problem?

**Comment by chrchang** [comment] 2017-11-14 19:06
Tried this on both OS X and Linux, with extra entries in the .sample file, and could not reproduce the problem.  You'll need to send me some sort of test case (hopefully smaller).

**Comment by azenin** [comment] 2017-11-15 17:09
Unfortunately, there is no way I can provide you data sample due to MTA restrictions.

**Comment by chrchang** [comment] 2017-11-15 17:40
Can you at least check whether you can isolate the problem to a subset of the data?  (A specific block of variants?)

What happens if you just perform the .bgen + .sample -> .pgen conversion (with "plink2 --bgen ... --sample ... --out tmp_data"), then run "plink2 --pfile tmp_data --validate"?

**Comment by azenin** [comment] 2017-12-27 12:48
All files described were made by slicing of initial bgen files using [bgenix](https://bitbucket.org/gavinband/bgen/wiki/bgenix) version: 1.0, revision d1f03a2

Validation:
```
master:/mnt/tmp$ plink2 --pfile test --validate
PLINK v2.00aLM 64-bit Intel (4 Nov 2017)       www.cog-genomics.org/plink/2.0/
(C) 2005-2017 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --pfile test
  --validate

Start time: Wed Dec 27 15:02:22 2017
122878 MB RAM detected; reserving 61439 MB for main workspace.
Using up to 16 threads (change this with --threads).
487409 samples (0 females, 0 males, 487409 ambiguous; 487409 founders) loaded
from test.psam.
1800000 variants loaded from test.pvar.
Validating test.pgen...
Error: Invalid 2-bit genotype record for (0-based) variant #0
End time: Wed Dec 27 15:02:23 2017
```
plink2 failed to read this pgen file for further processing like exporting. It says it's variant #0, so I sliced only this SNP and made validation
```
master:/mnt/tmp$ plink2 --pfile snp --validate
PLINK v2.00aLM 64-bit Intel (4 Nov 2017)       www.cog-genomics.org/plink/2.0/
(C) 2005-2017 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --pfile snp
  --validate

Start time: Wed Dec 27 14:59:35 2017
122878 MB RAM detected; reserving 61439 MB for main workspace.
Using up to 16 threads (change this with --threads).
487409 samples (0 females, 0 males, 487409 ambiguous; 487409 founders) loaded
from snp.psam.
1 variant loaded from snp.pvar.
Validating snp.pgen... done.
End time: Wed Dec 27 14:59:35 2017
```
Then I made another random slice:
```
master:/mnt/tmp$ bgenix -g chr5.bgen -incl-range 05:0-20000 > 20k.bgen

Welcome to bgenix
(version: 1.0, revision d1f03a2)

(C) 2009-2017 University of Oxford

Building query                                              :  (428/?,0.0s,384031.1/s)
Processing 428 variants                                     : [******************************] (428/428,0.7s,612.1/s)
bgenix: wrote data for 428 variants to stdout.

Thank you for using bgenix.
```
Converted and validated it:
```
master:/mnt/tmp$ plink2 --bgen 20k.bgen --sample imputed.sample --make-pgen --out 20k
PLINK v2.00aLM 64-bit Intel (4 Nov 2017)       www.cog-genomics.org/plink/2.0/
(C) 2005-2017 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to 20k.log.
Options in effect:
  --bgen 20k.bgen
  --make-pgen
  --out 20k
  --sample imputed.sample

Start time: Wed Dec 27 15:41:18 2017
122878 MB RAM detected; reserving 61439 MB for main workspace.
Using up to 16 threads (change this with --threads).
--bgen: 428 variants detected, format v1.2.
487409 samples imported from .sample file to 20k-temporary.psam .
--bgen: 20k-temporary.pgen + 20k-temporary.pvar written.
487409 samples (0 females, 0 males, 487409 ambiguous; 487409 founders) loaded
from 20k-temporary.psam.
428 variants loaded from 20k-temporary.pvar.
Note: No phenotype data present.
Writing 20k.pgen ... done.
Writing 20k.pvar ... done.
Writing 20k.psam ... done.
End time: Wed Dec 27 15:41:20 2017
master:/mnt/tmp$ plink2 --pfile 20k --validate
PLINK v2.00aLM 64-bit Intel (4 Nov 2017)       www.cog-genomics.org/plink/2.0/
(C) 2005-2017 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --pfile 20k
  --validate

Start time: Wed Dec 27 15:41:34 2017
122878 MB RAM detected; reserving 61439 MB for main workspace.
Using up to 16 threads (change this with --threads).
487409 samples (0 females, 0 males, 487409 ambiguous; 487409 founders) loaded
from 20k.psam.
428 variants loaded from 20k.pvar.
Validating 20k.pgen...
Error: Invalid 1-bit genotype record for (0-based) variant #2.
End time: Wed Dec 27 15:41:34 2017
```

**Comment by chrchang** [comment] 2017-12-28 00:59
There was a --validate bugfix on November 27th; retry this with a more recent build.

**Comment by chrchang** [comment] 2018-01-31 17:26
I believe the original bug is fixed in the 30 Jan 2018 build.  Sorry about the long delay in nailing this down.

**Closed** 2018-02-02 13:49 UTC
