### ISSUE TITLE
Windows Subsystem for Linux (WSL): Segmentation Fault (PLINK 1.9)

### ISSUE THREAD

**Issue by mjbeyeler** [chrchang/plink-ng#63] opened 2018-02-06 16:29 UTC
Hello!

I'd like to use PLINK 1.9 (Linux 64-bit) on my Windows 10 PC, using the fairly new WSL Ubuntu (https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

Unfortunately, when I try using it, I get a segmentation fault. Are any of you able to run PLINK 1.9 on Windows, or is there a general incompatibility btwn. WSL and PLINK 1.9 at the moment?

Best
Michael

**Comment by chrchang** [comment] 2018-02-06 17:37
It worked on my Windows 10 laptop the last time I tried it; I don't know whether that's because I was using a newer version of WSL, or there's some other reason.

Is there a reason you can't use the regular Windows 32- or 64-bit builds?

**Comment by MichaelBeyeler** [comment] 2018-02-06 17:48
The strange thing is, the Windows 64-bit version of PLINK 1.9 _runs_ in WSL, whereas the Linux 64-bit version doesn't (gives the segmentation fault).

The reason why I'd like to use the Linux version, is to program a script that works on both Windows and Ubuntu. I could program a workaround, but it would be awesome to get the Linux version to run on WSL.

**Comment by chrchang** [comment] 2018-02-06 18:19
Well, I actually got the Windows 10 laptop for the explicit purpose of investigating a WSL crash report a while ago, but "unfortunately" the Linux build ran fine...  If you're familiar with C, you could try inserting debug print statements and/or using a debugger to try to isolate where the segfault is occurring.

**Comment by MichaelBeyeler** [comment] 2018-05-03 09:52
@chrchang Are you sure that Plink 1.9 is working fine on WSL?

I have a new laptop now, I installed WSL, downloaded the latest Plink 1.9 stable beta, and then ran the toy example command

`./plink --file toy --freq --out toy_analysis`

which gives me the error

`PLINK v1.90p 64-bit (10 Apr 2018)              www.cog-genomics.org/plink/1.9/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to toy_analysis.log.
Options in effect:
  --file toy
  --freq
  --out toy_analysis

Segmentation fault (core dumped)`


The same command ran perfectly fine when using CMD Plink on the same laptop.

**Comment by chrchang** [comment] 2018-05-03 15:21
As I stated above, plink 1.9 appears to work on some WSL setups and not others, and unfortunately, the Windows 10 laptop I bought for the express purpose of trying to replicate WSL bug reports was not able to reproduce this.

Unless you can provide me a remote login which lets me e.g. inspect the core dump, and/or insert debug-prints and recompile until I've isolated the cause, you'll have to do that yourself and tell me what you find; it is not reasonable for me to spend thousands of dollars buying Windows machines with different configurations until I run into one that's similar enough to yours.

**Comment by MichaelBeyeler** [comment] 2018-05-03 15:40
That's perfectly understandable. Unfortunately I'm not proficient enough to do debug prints, but I'm lucky and PLINK2 alpha seems to work and also have all features that I currently need, so I guess I'll stick with PLINK2 for now.


Anyway, thanks for your responses!

**Comment by chrchang** [comment] 2019-10-06 16:34
Closing this since WSL2 exists, which should have improved compatibility across the board.

**Closed by chrchang** 2019-10-06 16:34 UTC
